### ISSUE TITLE
Key JLanguage has not been registered with the container.

### ISSUE THREAD

**Issue by DavidBoggitt** [asikart/quickicons#26]
Hi,

I've just installed version 2.0.3 (hotfix) on a clean install of Joomla 3.4.1.  The component is working on the frontend, but when I go to the component in the backend, I get this error message:

"Key JLanguage has not been registered with the container."

I really like this component - I was happy to pay for it too when it was commercial!  I hope you find the time to keep developing it :+1: 

Many thanks,

Dave.

**Comment by asika32764** [comment]
I think it is a B/C break of Joomla 3.4.1

Please wait us for the update.

**Comment by Media-Master** [comment]
Same problem here, had issues after updating Joomla to 3.4.1

**Comment by anirudh7** [comment]
Same here! "0 Key JLanguage has not been registered with the container."

**Comment by PascalNetenvie** [comment]
Same here !
But when i install by replacing files no problem ...

**Comment by an-walt** [comment]
I have the same problem (Version 2.04 on Joomla 3.4.1). Will there be an update or a workaround in the next time? 

@PascalNetenvie: What do you mean with "install it by replacing files"? 

Thanks in advance for your reply!

**Comment by juankadiaz** [comment]
Hi! great extension! any plans or estimated timing to solve this problem?

thanks a lot and great work!

**Comment by PascalNetenvie** [comment]
+1

**Comment by micker** [comment]
that broke popup media manager .... please correct it

**Comment by CKENT0369** [comment]
Great extension but having the same issue with 3.4.1. I installed it got it working good then updated to 3.4.1. I attempted to uninstall and reinstall same issues. To the person that said they got it to work overwriting the files, what did you do? Upload the files in its place or install from extension manager?

**Comment by phproberto** [comment]
@asika32764 I sent a pull request (https://github.com/ventoviro/windwalker-joomla-rad/pull/118) to solve the issue.

**Comment by CKENT0369** [comment]
I can at least get into it now. I have another issue to fix though. Pretty sure it is unrelated so I will start another bug.

**Comment by iamrobert** [comment]
Hi - I have tried installing:
1. hotfix version
2. overwriting  src/DI/Container.php with:
https://github.com/phproberto/windwalker-joomla-rad/blob/parent-aliases/src/DI/Container.php
But - I still get the:
"Key JLanguage has not been registered with the container."

IS there something I have missed?

**Comment by CKENT0369** [comment]
try clearing cache

**Comment by pcminute** [comment]
good job..think's is Work.  ;-) @phproberto

**Comment by PascalNetenvie** [comment]
Hi,
Thanks Roberto.
If i fix file manually after install it work fine.
But i fix the 2 files (this file is present 2 times) in extension archive and install/upgrade file is not fixed ....
Why this ?

**Comment by phproberto** [comment]
@PascalNetenvie you only have to unzip and replace:

`com_quickicons-2.0.3-hotfix-for-j3.4/windwalker/src/DI/Container.php`

with:

https://raw.githubusercontent.com/phproberto/windwalker-joomla-rad/parent-aliases/src/DI/Container.php

Then zip again and the component should work.

But I think @asika32764 is going to release a fixed version soon so is better to wait to the official version.

**Comment by asika32764** [comment]
Fixed in [2.0.4](https://github.com/asikart/quickicons/releases/tag/2.0.4)

Please take a try.

**Comment by DavidBoggitt** [comment]
Thanks - I'll install a clean 3.4.1 first.  Are you hoping to fix this bug https://github.com/asikart/quickicons/issues/25 in version 2.0.5?

Also, in the 2.0.4 zip file, I think some information in the update.xml is incorrect.

Thanks for looking at this :)

Dave.

**Comment by asika32764** [comment]
It's will take some time to find the reason of #25 , so I fix the error first in 2.0.4.

The update.xml works find in staging branch, so I didn't correct it in master branch.

**Comment by DavidBoggitt** [comment]
OK - thanks Simon.  This is a great extension for making Joomla's backend more user-friendly and I'm grateful to you for continuing your development.

**Comment by postkat** [comment]
Same problem here; Quickicons version 2.0.4 om Joomla 3.4.3.
I have tried to uninstall first but the problem remains.

Dorine

**Comment by waynejb** [comment]
Basically what we had to do is install the older version then manually update each files from the new package.
